// DeciderDisplayEnable, Version 1.0.0, vom 25.09.2013
//
// Zeigt alle Unterdrückten Meldungen in einer Liste an
// and ermöglicht durch entfernen der jeweiligen Checkbox
// das wiederanzeigen der unterdrückten Meldung.
//
// Copyright by Frank Schöneck, 2013
// letzte Änderung: Frank Schöneck, 25.09.2013 V1.0.0, -Projektbeginn
//
// für Eplan Electric P8, V2.2 / V2.3
//

// DeciderDisplayEnable, Version 1.0.0, dated 25.09.2013
//
// Displays all suppressed messages in a list
// and allows by removing the respective checkbox
// the replay of the suppressed message.
//
// Copyright by Frank Schöneck, 2013
// last change: Justin Walz, 02/16/2018 V1.0.1, translated to english
//
// for Eplan Electric P8, V2.2 / V2.3
//

using System.Windows.Forms;
using Eplan.EplApi.Scripting;
using Eplan.EplApi.Base;

public partial class frmDeciderDisplayEnable : System.Windows.Forms.Form
{
	private ListView listView1;
	private ColumnHeader Dialog;
	private ColumnHeader Index;
	private Button btnOK;
	private Button btnAbort;

    #region Code generated by Windows Form Designer

    // <summary>
    // Required designer variable.
    // </ summary>

    private System.ComponentModel.IContainer components = null;

    // <summary>
    // Purge used resources.
    // </ summary>
    // <param name = "disposing"> True, if managed resources
    // should be deleted; otherwise False. </ param>

    protected override void Dispose(bool disposing)
	{
		if (disposing && (components != null))
		{
			components.Dispose();
		}
		base.Dispose(disposing);
	}

    // <summary>
    // Required method for designer support.
    // The content of the method must not be used with the code editor
    // to be changed.
    // </ summary>

    private void InitializeComponent()
	{
            this.listView1 = new System.Windows.Forms.ListView();
            this.Dialog = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.Index = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.btnOK = new System.Windows.Forms.Button();
            this.btnAbort = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // listView1
            // 
            this.listView1.CheckBoxes = true;
            this.listView1.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.Dialog,
            this.Index});
            this.listView1.FullRowSelect = true;
            this.listView1.HeaderStyle = System.Windows.Forms.ColumnHeaderStyle.Nonclickable;
            this.listView1.Location = new System.Drawing.Point(12, 12);
            this.listView1.MultiSelect = false;
            this.listView1.Name = "listView1";
            this.listView1.Size = new System.Drawing.Size(319, 202);
            this.listView1.TabIndex = 0;
            this.listView1.UseCompatibleStateImageBehavior = false;
            this.listView1.View = System.Windows.Forms.View.Details;
            // 
            // Dialog
            // 
            this.Dialog.Text = "Dialog";
            this.Dialog.Width = 270;
            // 
            // Index
            // 
            this.Index.Text = "Index";
            this.Index.Width = 40;
            // 
            // btnOK
            // 
            this.btnOK.Location = new System.Drawing.Point(141, 226);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new System.Drawing.Size(92, 27);
            this.btnOK.TabIndex = 1;
            this.btnOK.Text = "OK";
            this.btnOK.UseVisualStyleBackColor = true;
            this.btnOK.Click += new System.EventHandler(this.btnOK_Click);
            // 
            // btnAbort
            // 
            this.btnAbort.Location = new System.Drawing.Point(239, 226);
            this.btnAbort.Name = "btnAbort";
            this.btnAbort.Size = new System.Drawing.Size(92, 27);
            this.btnAbort.TabIndex = 2;
            this.btnAbort.Text = "Abort";
            this.btnAbort.UseVisualStyleBackColor = true;
            this.btnAbort.Click += new System.EventHandler(this.btnAbort_Click);
            // 
            // frmDeciderDisplayEnable
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(345, 265);
            this.Controls.Add(this.btnAbort);
            this.Controls.Add(this.btnOK);
            this.Controls.Add(this.listView1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmDeciderDisplayEnable";
            this.ShowIcon = false;
            this.ShowInTaskbar = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Suppressed messages";
            this.Load += new System.EventHandler(this.frmDeciderDisplayEnable_Load);
            this.ResumeLayout(false);

	}

	public frmDeciderDisplayEnable()
	{
		InitializeComponent();
	}

	#endregion

	[Start]
	public void Function()
	{
        // Show form

        frmDeciderDisplayEnable frm = new frmDeciderDisplayEnable();
		frm.ShowDialog();

		return;
	}

	private void frmDeciderDisplayEnable_Load(object sender, System.EventArgs e)
	{
		Settings oSettings = new Settings();
		string sDeciderNotDisplay = string.Empty;
		int iCountDeciderNotDisplay = 0;
		ListViewItem objListViewItem = new ListViewItem();

		if (oSettings.ExistSetting("USER.Decider.NotDisplay"))
		{
            // Determine number of settings

            iCountDeciderNotDisplay = oSettings.GetCountOfValues("USER.Decider.NotDisplay");

            // Read in list view


            for (int n = 0; n < iCountDeciderNotDisplay; n++)
			{
				sDeciderNotDisplay = oSettings.GetStringSetting("USER.Decider.NotDisplay", n);
				objListViewItem = new ListViewItem();
				objListViewItem.Text = sDeciderNotDisplay;
				objListViewItem.Checked = true;
				objListViewItem.SubItems.Add(n.ToString());
				listView1.Items.Add(objListViewItem);
			}
		}
	}

	// Button OK

	private void btnOK_Click(object sender, System.EventArgs e)
	{
		Settings oSettings = new Settings();

        // Setting clear!

        oSettings.DeleteSetting("USER.Decider.NotDisplay");

        // Create a new setting after deleting

        oSettings.AddStringSetting("USER.Decider.NotDisplay",
		new string[] { },
		new string[] { }, "DeciderDisplayEnable",
		new string[] { "Default value of DeciderDisplayEnable" },
		ISettings.CreationFlag.Insert);

		int n = 0; // Start counter

        // Execute list view

        foreach (ListViewItem itemRow in listView1.Items)
		{
			if (itemRow.Checked) // When Selected Write Setting
            {
                // Write a setting

                oSettings.SetStringSetting("USER.Decider.NotDisplay", itemRow.Text, n);
				n++; // Increase counter for VAL

            }
		}

        // Break up


        Close();
	}

	// Button Abort

	private void btnAbort_Click(object sender, System.EventArgs e)
	{
		Close();
	}
}