// LocationPrint.cs
//
// Beschreibung:
// Stromlaufpläne nach Placen sPlaceiert topress.
// Im Auswahlfeld einen Place auswählen oder eingeben und die Stromlaufplanpages für den gewählten Place werden
// ausgedruckt
// Wildcards werden mitberücksichtigt (* und &)
// z.B.Place1: KK1 --> alle pages mit Bauteilen in +KK1 werden ausgedruckt
// z.B.Place5: S* --> alle pages mit Bauteilen in +S1, +S2, +S3...werden ausgedruckt
// wenn der Hacken bei "Place Seperate" gesetzt wird werden eingaben mit Wildcards vereinzelt ausgewertet: 
// Z.B.alle Bedienstellen im Stromlaufplan heißen +BKx, wenn der Hacken gesetzt ist und die Eingabe BK* bekommt man
// von jeder Bedienstelle die Pläne sPlaceiert ausgedruckt BK1, BK2, BK3 ….
// Die pages werden Bauteileorientiert gedruckt. 
// Wenn die Eingabe BK1 ist und auf einer Seite mit einem BK1 Bauteil im Rahmen +KK5 steht,   
// wird die Seite gedruckt
//
// Es werden folgende pagestypen berücksichtigt: Schaltplan allpolig, Schaltplan einpolig, Übersicht, Grafik, Schaltschrankaufbau
//
//
// 12.02.2018   Artur Netz  V1.0
//

// LocationPrint.cs
//
// Description:
// Print circuit diagrams sPlaced by location.
// Select or enter a location in the selection box and the circuit diagram pages for the selected location
// printed
// Wildcards are included (* and &)
// say place1: KK1 -> all pages with parts in + KK1 are printed out
// For example, location5: S * -> all pages with components in + S1, + S2, + S3 ... are printed out
// if the hack is set at "Separate Locations", entries with wildcards are evaluated occasionally:
// Z.Ball control panels in the circuit diagram are called + BKx, if the hacking is set and you get the input BK *
// the charts sPlaced out of every control unit BK1, BK2, BK3 ....
// The pages are printed component-oriented.
// If the input is BK1 and is on a page with a BK1 component in frame + KK5,
// the page is printed
//
// The following page types are considered: Circuit diagram all-pole, circuit diagram single-pole, overview, graphics, cabinet layout
//
//
// 12.02.2018 Artur net V1.0
//

using System;
using System.Windows.Forms;
using System.IO;
using Eplan.EplApi.Scripting;
using Eplan.EplApi.ApplicationFramework;
using Eplan.EplApi.Base;
using System.Drawing.Printing;
using System.Text.RegularExpressions;

public partial class frmMain : System.Windows.Forms.Form
{
    private Button btnPrint;
    private Label lblLocation1;
    private ComboBox cobxPlace1;
    private Label lblLocation2;
    private ComboBox cobxPlace2;
    private Label lblLocation3;
    private ComboBox cobxPlace3;
    private Label lblLocation4;
    private ComboBox cobxPlace4;
    private Label lblLocation5;
    private ComboBox cobxPlace5;
    private Label lblLocation6;
    private ComboBox cobxPlace6;
    private Label lblLocation7;
    private ComboBox cobxPlace7;
    private Label lblLocation8;
    private ComboBox cobxPlace8;
    private Label lblLocation9;
    private ComboBox cobxPlace9;
    private Label lblLocation10;
    private ComboBox cobxPlace10;
    private ComboBox cobxSelectPrinter;
    private Label label13;
    private Label label14;
    private Label label15;
    private GroupBox grbxInfo;
    private GroupBox grbxLocations;
    private GroupBox grbxPrint;
    private ComboBox cobxPlace11;
    private ComboBox cobxPlace12;
    private Label lblLocation12;
    private Label lblLocation11;
    private CheckBox chbxPlace12;
    private CheckBox chbxPlace11;
    private CheckBox chbxPlace10;
    private CheckBox chbxPlace9;
    private CheckBox chbxPlace8;
    private CheckBox chbxPlace7;
    private CheckBox chbxPlace6;
    private CheckBox chbxPlace5;
    private CheckBox chbxPlace4;
    private CheckBox chbxPlace3;
    private CheckBox chbxPlace2;
    private CheckBox chbxPlace1;
    private Button btnReset;
    private Label lbl1;
    private Label label1;
    #region Code generated by Windows Form Designer

    /// <summary>
    /// Required designer variable.
    /// </summary>
    private System.ComponentModel.IContainer components = null;

    /// <summary>
    /// Clean used resources.
    /// </summary>
    /// <param name="disposing">True, when managed resources are to be deleted; otherwise False.</param>
    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }
        base.Dispose(disposing);
    }

    /// <summary>
    /// Required method for designer suppPlace.
    /// The content of the method must not be changed with the code editor.
    /// </summary>
    private void InitializeComponent()
    {
            this.btnPrint = new System.Windows.Forms.Button();
            this.lblLocation1 = new System.Windows.Forms.Label();
            this.cobxPlace1 = new System.Windows.Forms.ComboBox();
            this.lblLocation2 = new System.Windows.Forms.Label();
            this.cobxPlace2 = new System.Windows.Forms.ComboBox();
            this.lblLocation3 = new System.Windows.Forms.Label();
            this.cobxPlace3 = new System.Windows.Forms.ComboBox();
            this.lblLocation4 = new System.Windows.Forms.Label();
            this.cobxPlace4 = new System.Windows.Forms.ComboBox();
            this.lblLocation5 = new System.Windows.Forms.Label();
            this.cobxPlace5 = new System.Windows.Forms.ComboBox();
            this.lblLocation6 = new System.Windows.Forms.Label();
            this.cobxPlace6 = new System.Windows.Forms.ComboBox();
            this.lblLocation7 = new System.Windows.Forms.Label();
            this.cobxPlace7 = new System.Windows.Forms.ComboBox();
            this.lblLocation8 = new System.Windows.Forms.Label();
            this.cobxPlace8 = new System.Windows.Forms.ComboBox();
            this.lblLocation9 = new System.Windows.Forms.Label();
            this.cobxPlace9 = new System.Windows.Forms.ComboBox();
            this.lblLocation10 = new System.Windows.Forms.Label();
            this.cobxPlace10 = new System.Windows.Forms.ComboBox();
            this.cobxSelectPrinter = new System.Windows.Forms.ComboBox();
            this.label13 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.label15 = new System.Windows.Forms.Label();
            this.grbxInfo = new System.Windows.Forms.GroupBox();
            this.grbxLocations = new System.Windows.Forms.GroupBox();
            this.lbl1 = new System.Windows.Forms.Label();
            this.chbxPlace12 = new System.Windows.Forms.CheckBox();
            this.chbxPlace11 = new System.Windows.Forms.CheckBox();
            this.chbxPlace10 = new System.Windows.Forms.CheckBox();
            this.chbxPlace9 = new System.Windows.Forms.CheckBox();
            this.chbxPlace8 = new System.Windows.Forms.CheckBox();
            this.chbxPlace7 = new System.Windows.Forms.CheckBox();
            this.chbxPlace6 = new System.Windows.Forms.CheckBox();
            this.chbxPlace5 = new System.Windows.Forms.CheckBox();
            this.chbxPlace4 = new System.Windows.Forms.CheckBox();
            this.chbxPlace3 = new System.Windows.Forms.CheckBox();
            this.chbxPlace2 = new System.Windows.Forms.CheckBox();
            this.chbxPlace1 = new System.Windows.Forms.CheckBox();
            this.cobxPlace11 = new System.Windows.Forms.ComboBox();
            this.cobxPlace12 = new System.Windows.Forms.ComboBox();
            this.lblLocation12 = new System.Windows.Forms.Label();
            this.lblLocation11 = new System.Windows.Forms.Label();
            this.grbxPrint = new System.Windows.Forms.GroupBox();
            this.btnReset = new System.Windows.Forms.Button();
            this.label1 = new System.Windows.Forms.Label();
            this.grbxInfo.SuspendLayout();
            this.grbxLocations.SuspendLayout();
            this.grbxPrint.SuspendLayout();
            this.SuspendLayout();
            // 
            // btnPrint
            // 
            this.btnPrint.Location = new System.Drawing.Point(85, 549);
            this.btnPrint.Name = "btnPrint";
            this.btnPrint.Size = new System.Drawing.Size(168, 30);
            this.btnPrint.TabIndex = 0;
            this.btnPrint.Text = "To press";
            this.btnPrint.UseVisualStyleBackColor = true;
            this.btnPrint.Click += new System.EventHandler(this.btnPrint_Click);
            // 
            // lblLocation1
            // 
            this.lblLocation1.AutoSize = true;
            this.lblLocation1.Location = new System.Drawing.Point(8, 36);
            this.lblLocation1.Name = "lblLocation1";
            this.lblLocation1.Size = new System.Drawing.Size(43, 13);
            this.lblLocation1.TabIndex = 3;
            this.lblLocation1.Text = "Place 1";
            // 
            // cobxPlace1
            // 
            this.cobxPlace1.FormattingEnabled = true;
            this.cobxPlace1.Location = new System.Drawing.Point(58, 33);
            this.cobxPlace1.Name = "cobxPlace1";
            this.cobxPlace1.Size = new System.Drawing.Size(207, 21);
            this.cobxPlace1.TabIndex = 48;
            // 
            // lblLocation2
            // 
            this.lblLocation2.AutoSize = true;
            this.lblLocation2.Location = new System.Drawing.Point(8, 63);
            this.lblLocation2.Name = "lblLocation2";
            this.lblLocation2.Size = new System.Drawing.Size(43, 13);
            this.lblLocation2.TabIndex = 47;
            this.lblLocation2.Text = "Place 2";
            // 
            // cobxPlace2
            // 
            this.cobxPlace2.FormattingEnabled = true;
            this.cobxPlace2.Location = new System.Drawing.Point(58, 60);
            this.cobxPlace2.Name = "cobxPlace2";
            this.cobxPlace2.Size = new System.Drawing.Size(207, 21);
            this.cobxPlace2.TabIndex = 50;
            // 
            // lblLocation3
            // 
            this.lblLocation3.AutoSize = true;
            this.lblLocation3.Location = new System.Drawing.Point(8, 90);
            this.lblLocation3.Name = "lblLocation3";
            this.lblLocation3.Size = new System.Drawing.Size(43, 13);
            this.lblLocation3.TabIndex = 49;
            this.lblLocation3.Text = "Place 3";
            // 
            // cobxPlace3
            // 
            this.cobxPlace3.FormattingEnabled = true;
            this.cobxPlace3.Location = new System.Drawing.Point(58, 87);
            this.cobxPlace3.Name = "cobxPlace3";
            this.cobxPlace3.Size = new System.Drawing.Size(207, 21);
            this.cobxPlace3.TabIndex = 52;
            // 
            // lblLocation4
            // 
            this.lblLocation4.AutoSize = true;
            this.lblLocation4.Location = new System.Drawing.Point(8, 117);
            this.lblLocation4.Name = "lblLocation4";
            this.lblLocation4.Size = new System.Drawing.Size(43, 13);
            this.lblLocation4.TabIndex = 51;
            this.lblLocation4.Text = "Place 4";
            // 
            // cobxPlace4
            // 
            this.cobxPlace4.FormattingEnabled = true;
            this.cobxPlace4.Location = new System.Drawing.Point(58, 114);
            this.cobxPlace4.Name = "cobxPlace4";
            this.cobxPlace4.Size = new System.Drawing.Size(207, 21);
            this.cobxPlace4.TabIndex = 54;
            // 
            // lblLocation5
            // 
            this.lblLocation5.AutoSize = true;
            this.lblLocation5.Location = new System.Drawing.Point(8, 144);
            this.lblLocation5.Name = "lblLocation5";
            this.lblLocation5.Size = new System.Drawing.Size(43, 13);
            this.lblLocation5.TabIndex = 53;
            this.lblLocation5.Text = "Place 5";
            // 
            // cobxPlace5
            // 
            this.cobxPlace5.FormattingEnabled = true;
            this.cobxPlace5.Location = new System.Drawing.Point(58, 141);
            this.cobxPlace5.Name = "cobxPlace5";
            this.cobxPlace5.Size = new System.Drawing.Size(207, 21);
            this.cobxPlace5.TabIndex = 56;
            // 
            // lblLocation6
            // 
            this.lblLocation6.AutoSize = true;
            this.lblLocation6.Location = new System.Drawing.Point(8, 171);
            this.lblLocation6.Name = "lblLocation6";
            this.lblLocation6.Size = new System.Drawing.Size(43, 13);
            this.lblLocation6.TabIndex = 55;
            this.lblLocation6.Text = "Place 6";
            // 
            // cobxPlace6
            // 
            this.cobxPlace6.FormattingEnabled = true;
            this.cobxPlace6.Location = new System.Drawing.Point(58, 168);
            this.cobxPlace6.Name = "cobxPlace6";
            this.cobxPlace6.Size = new System.Drawing.Size(207, 21);
            this.cobxPlace6.TabIndex = 58;
            // 
            // lblLocation7
            // 
            this.lblLocation7.AutoSize = true;
            this.lblLocation7.Location = new System.Drawing.Point(8, 198);
            this.lblLocation7.Name = "lblLocation7";
            this.lblLocation7.Size = new System.Drawing.Size(43, 13);
            this.lblLocation7.TabIndex = 57;
            this.lblLocation7.Text = "Place 7";
            // 
            // cobxPlace7
            // 
            this.cobxPlace7.FormattingEnabled = true;
            this.cobxPlace7.Location = new System.Drawing.Point(58, 195);
            this.cobxPlace7.Name = "cobxPlace7";
            this.cobxPlace7.Size = new System.Drawing.Size(207, 21);
            this.cobxPlace7.TabIndex = 60;
            // 
            // lblLocation8
            // 
            this.lblLocation8.AutoSize = true;
            this.lblLocation8.Location = new System.Drawing.Point(8, 225);
            this.lblLocation8.Name = "lblLocation8";
            this.lblLocation8.Size = new System.Drawing.Size(43, 13);
            this.lblLocation8.TabIndex = 59;
            this.lblLocation8.Text = "Place 8";
            // 
            // cobxPlace8
            // 
            this.cobxPlace8.FormattingEnabled = true;
            this.cobxPlace8.Location = new System.Drawing.Point(58, 222);
            this.cobxPlace8.Name = "cobxPlace8";
            this.cobxPlace8.Size = new System.Drawing.Size(207, 21);
            this.cobxPlace8.TabIndex = 62;
            // 
            // lblLocation9
            // 
            this.lblLocation9.AutoSize = true;
            this.lblLocation9.Location = new System.Drawing.Point(8, 252);
            this.lblLocation9.Name = "lblLocation9";
            this.lblLocation9.Size = new System.Drawing.Size(43, 13);
            this.lblLocation9.TabIndex = 61;
            this.lblLocation9.Text = "Place 9";
            // 
            // cobxPlace9
            // 
            this.cobxPlace9.FormattingEnabled = true;
            this.cobxPlace9.Location = new System.Drawing.Point(58, 249);
            this.cobxPlace9.Name = "cobxPlace9";
            this.cobxPlace9.Size = new System.Drawing.Size(207, 21);
            this.cobxPlace9.TabIndex = 64;
            // 
            // lblLocation10
            // 
            this.lblLocation10.AutoSize = true;
            this.lblLocation10.Location = new System.Drawing.Point(8, 279);
            this.lblLocation10.Name = "lblLocation10";
            this.lblLocation10.Size = new System.Drawing.Size(49, 13);
            this.lblLocation10.TabIndex = 63;
            this.lblLocation10.Text = "Place 10";
            // 
            // cobxPlace10
            // 
            this.cobxPlace10.FormattingEnabled = true;
            this.cobxPlace10.Location = new System.Drawing.Point(58, 276);
            this.cobxPlace10.Name = "cobxPlace10";
            this.cobxPlace10.Size = new System.Drawing.Size(207, 21);
            this.cobxPlace10.TabIndex = 65;
            // 
            // cobxSelectPrinter
            // 
            this.cobxSelectPrinter.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cobxSelectPrinter.FormattingEnabled = true;
            this.cobxSelectPrinter.Location = new System.Drawing.Point(56, 19);
            this.cobxSelectPrinter.Name = "cobxSelectPrinter";
            this.cobxSelectPrinter.Size = new System.Drawing.Size(360, 21);
            this.cobxSelectPrinter.TabIndex = 67;
            // 
            // label13
            // 
            this.label13.AutoSize = true;
            this.label13.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label13.Location = new System.Drawing.Point(6, 16);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(224, 13);
            this.label13.TabIndex = 69;
            this.label13.Text = "Separation of several places with; (Semicolon)";
            // 
            // label14
            // 
            this.label14.AutoSize = true;
            this.label14.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label14.Location = new System.Drawing.Point(6, 31);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(57, 13);
            this.label14.TabIndex = 70;
            this.label14.Text = "Wildcards:";
            // 
            // label15
            // 
            this.label15.AutoSize = true;
            this.label15.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label15.Location = new System.Drawing.Point(18, 46);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(365, 13);
            this.label15.TabIndex = 71;
            this.label15.Text = "S* --> Prints all places that start with S ? ->Print all places the S + 1 said have";
            this.label15.Click += new System.EventHandler(this.label15_Click);
            // 
            // grbxInfo
            // 
            this.grbxInfo.Controls.Add(this.label13);
            this.grbxInfo.Controls.Add(this.label15);
            this.grbxInfo.Controls.Add(this.label14);
            this.grbxInfo.Location = new System.Drawing.Point(27, 28);
            this.grbxInfo.Name = "grbxInfo";
            this.grbxInfo.Size = new System.Drawing.Size(421, 82);
            this.grbxInfo.TabIndex = 72;
            this.grbxInfo.TabStop = false;
            this.grbxInfo.Text = "Info";
            // 
            // grbxLocations
            // 
            this.grbxLocations.Controls.Add(this.lbl1);
            this.grbxLocations.Controls.Add(this.chbxPlace12);
            this.grbxLocations.Controls.Add(this.chbxPlace11);
            this.grbxLocations.Controls.Add(this.chbxPlace10);
            this.grbxLocations.Controls.Add(this.chbxPlace9);
            this.grbxLocations.Controls.Add(this.chbxPlace8);
            this.grbxLocations.Controls.Add(this.chbxPlace7);
            this.grbxLocations.Controls.Add(this.chbxPlace6);
            this.grbxLocations.Controls.Add(this.chbxPlace5);
            this.grbxLocations.Controls.Add(this.chbxPlace4);
            this.grbxLocations.Controls.Add(this.chbxPlace3);
            this.grbxLocations.Controls.Add(this.chbxPlace2);
            this.grbxLocations.Controls.Add(this.chbxPlace1);
            this.grbxLocations.Controls.Add(this.cobxPlace11);
            this.grbxLocations.Controls.Add(this.cobxPlace12);
            this.grbxLocations.Controls.Add(this.lblLocation12);
            this.grbxLocations.Controls.Add(this.lblLocation11);
            this.grbxLocations.Controls.Add(this.lblLocation1);
            this.grbxLocations.Controls.Add(this.lblLocation2);
            this.grbxLocations.Controls.Add(this.cobxPlace1);
            this.grbxLocations.Controls.Add(this.lblLocation3);
            this.grbxLocations.Controls.Add(this.cobxPlace10);
            this.grbxLocations.Controls.Add(this.cobxPlace2);
            this.grbxLocations.Controls.Add(this.cobxPlace9);
            this.grbxLocations.Controls.Add(this.lblLocation4);
            this.grbxLocations.Controls.Add(this.lblLocation10);
            this.grbxLocations.Controls.Add(this.cobxPlace3);
            this.grbxLocations.Controls.Add(this.cobxPlace8);
            this.grbxLocations.Controls.Add(this.lblLocation5);
            this.grbxLocations.Controls.Add(this.lblLocation9);
            this.grbxLocations.Controls.Add(this.cobxPlace4);
            this.grbxLocations.Controls.Add(this.cobxPlace7);
            this.grbxLocations.Controls.Add(this.lblLocation6);
            this.grbxLocations.Controls.Add(this.lblLocation8);
            this.grbxLocations.Controls.Add(this.cobxPlace5);
            this.grbxLocations.Controls.Add(this.cobxPlace6);
            this.grbxLocations.Controls.Add(this.lblLocation7);
            this.grbxLocations.Location = new System.Drawing.Point(25, 117);
            this.grbxLocations.Name = "grbxLocations";
            this.grbxLocations.Size = new System.Drawing.Size(423, 359);
            this.grbxLocations.TabIndex = 73;
            this.grbxLocations.TabStop = false;
            this.grbxLocations.Text = "Place";
            // 
            // lbl1
            // 
            this.lbl1.AutoSize = true;
            this.lbl1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbl1.Location = new System.Drawing.Point(217, 13);
            this.lbl1.Name = "lbl1";
            this.lbl1.Size = new System.Drawing.Size(79, 13);
            this.lbl1.TabIndex = 72;
            this.lbl1.Text = "Separate place";
            // 
            // chbxPlace12
            // 
            this.chbxPlace12.AutoSize = true;
            this.chbxPlace12.Location = new System.Drawing.Point(274, 333);
            this.chbxPlace12.Name = "chbxPlace12";
            this.chbxPlace12.Size = new System.Drawing.Size(15, 14);
            this.chbxPlace12.TabIndex = 83;
            this.chbxPlace12.UseVisualStyleBackColor = true;
            // 
            // chbxPlace11
            // 
            this.chbxPlace11.AutoSize = true;
            this.chbxPlace11.Location = new System.Drawing.Point(274, 306);
            this.chbxPlace11.Name = "chbxPlace11";
            this.chbxPlace11.Size = new System.Drawing.Size(15, 14);
            this.chbxPlace11.TabIndex = 82;
            this.chbxPlace11.UseVisualStyleBackColor = true;
            // 
            // chbxPlace10
            // 
            this.chbxPlace10.AutoSize = true;
            this.chbxPlace10.Location = new System.Drawing.Point(274, 279);
            this.chbxPlace10.Name = "chbxPlace10";
            this.chbxPlace10.Size = new System.Drawing.Size(15, 14);
            this.chbxPlace10.TabIndex = 81;
            this.chbxPlace10.UseVisualStyleBackColor = true;
            // 
            // chbxPlace9
            // 
            this.chbxPlace9.AutoSize = true;
            this.chbxPlace9.Location = new System.Drawing.Point(274, 252);
            this.chbxPlace9.Name = "chbxPlace9";
            this.chbxPlace9.Size = new System.Drawing.Size(15, 14);
            this.chbxPlace9.TabIndex = 80;
            this.chbxPlace9.UseVisualStyleBackColor = true;
            // 
            // chbxPlace8
            // 
            this.chbxPlace8.AutoSize = true;
            this.chbxPlace8.Location = new System.Drawing.Point(274, 225);
            this.chbxPlace8.Name = "chbxPlace8";
            this.chbxPlace8.Size = new System.Drawing.Size(15, 14);
            this.chbxPlace8.TabIndex = 79;
            this.chbxPlace8.UseVisualStyleBackColor = true;
            // 
            // chbxPlace7
            // 
            this.chbxPlace7.AutoSize = true;
            this.chbxPlace7.Location = new System.Drawing.Point(274, 198);
            this.chbxPlace7.Name = "chbxPlace7";
            this.chbxPlace7.Size = new System.Drawing.Size(15, 14);
            this.chbxPlace7.TabIndex = 78;
            this.chbxPlace7.UseVisualStyleBackColor = true;
            // 
            // chbxPlace6
            // 
            this.chbxPlace6.AutoSize = true;
            this.chbxPlace6.Location = new System.Drawing.Point(274, 171);
            this.chbxPlace6.Name = "chbxPlace6";
            this.chbxPlace6.Size = new System.Drawing.Size(15, 14);
            this.chbxPlace6.TabIndex = 77;
            this.chbxPlace6.UseVisualStyleBackColor = true;
            // 
            // chbxPlace5
            // 
            this.chbxPlace5.AutoSize = true;
            this.chbxPlace5.Location = new System.Drawing.Point(274, 144);
            this.chbxPlace5.Name = "chbxPlace5";
            this.chbxPlace5.Size = new System.Drawing.Size(15, 14);
            this.chbxPlace5.TabIndex = 76;
            this.chbxPlace5.UseVisualStyleBackColor = true;
            // 
            // chbxPlace4
            // 
            this.chbxPlace4.AutoSize = true;
            this.chbxPlace4.Location = new System.Drawing.Point(274, 117);
            this.chbxPlace4.Name = "chbxPlace4";
            this.chbxPlace4.Size = new System.Drawing.Size(15, 14);
            this.chbxPlace4.TabIndex = 75;
            this.chbxPlace4.UseVisualStyleBackColor = true;
            // 
            // chbxPlace3
            // 
            this.chbxPlace3.AutoSize = true;
            this.chbxPlace3.Location = new System.Drawing.Point(274, 90);
            this.chbxPlace3.Name = "chbxPlace3";
            this.chbxPlace3.Size = new System.Drawing.Size(15, 14);
            this.chbxPlace3.TabIndex = 72;
            this.chbxPlace3.UseVisualStyleBackColor = true;
            // 
            // chbxPlace2
            // 
            this.chbxPlace2.AutoSize = true;
            this.chbxPlace2.Location = new System.Drawing.Point(274, 63);
            this.chbxPlace2.Name = "chbxPlace2";
            this.chbxPlace2.Size = new System.Drawing.Size(15, 14);
            this.chbxPlace2.TabIndex = 71;
            this.chbxPlace2.UseVisualStyleBackColor = true;
            // 
            // chbxPlace1
            // 
            this.chbxPlace1.AutoSize = true;
            this.chbxPlace1.Location = new System.Drawing.Point(274, 36);
            this.chbxPlace1.Name = "chbxPlace1";
            this.chbxPlace1.Size = new System.Drawing.Size(15, 14);
            this.chbxPlace1.TabIndex = 70;
            this.chbxPlace1.UseVisualStyleBackColor = true;
            // 
            // cobxPlace11
            // 
            this.cobxPlace11.FormattingEnabled = true;
            this.cobxPlace11.Location = new System.Drawing.Point(58, 303);
            this.cobxPlace11.Name = "cobxPlace11";
            this.cobxPlace11.Size = new System.Drawing.Size(207, 21);
            this.cobxPlace11.TabIndex = 69;
            // 
            // cobxPlace12
            // 
            this.cobxPlace12.FormattingEnabled = true;
            this.cobxPlace12.Location = new System.Drawing.Point(58, 330);
            this.cobxPlace12.Name = "cobxPlace12";
            this.cobxPlace12.Size = new System.Drawing.Size(207, 21);
            this.cobxPlace12.TabIndex = 68;
            // 
            // lblLocation12
            // 
            this.lblLocation12.AutoSize = true;
            this.lblLocation12.Location = new System.Drawing.Point(8, 333);
            this.lblLocation12.Name = "lblLocation12";
            this.lblLocation12.Size = new System.Drawing.Size(49, 13);
            this.lblLocation12.TabIndex = 67;
            this.lblLocation12.Text = "Place 12";
            // 
            // lblLocation11
            // 
            this.lblLocation11.AutoSize = true;
            this.lblLocation11.Location = new System.Drawing.Point(8, 306);
            this.lblLocation11.Name = "lblLocation11";
            this.lblLocation11.Size = new System.Drawing.Size(49, 13);
            this.lblLocation11.TabIndex = 66;
            this.lblLocation11.Text = "Place 11";
            // 
            // grbxPrint
            // 
            this.grbxPrint.Controls.Add(this.cobxSelectPrinter);
            this.grbxPrint.Location = new System.Drawing.Point(25, 484);
            this.grbxPrint.Name = "grbxPrint";
            this.grbxPrint.Size = new System.Drawing.Size(423, 56);
            this.grbxPrint.TabIndex = 74;
            this.grbxPrint.TabStop = false;
            this.grbxPrint.Text = "Select printer";
            // 
            // btnReset
            // 
            this.btnReset.Location = new System.Drawing.Point(282, 549);
            this.btnReset.Name = "btnReset";
            this.btnReset.Size = new System.Drawing.Size(44, 30);
            this.btnReset.TabIndex = 75;
            this.btnReset.Text = "Reset";
            this.btnReset.UseVisualStyleBackColor = true;
            this.btnReset.Click += new System.EventHandler(this.btnReset_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(24, 9);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(155, 16);
            this.label1.TabIndex = 2;
            this.label1.Text = "After placing placed print";
            // 
            // frmMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(515, 597);
            this.Controls.Add(this.btnReset);
            this.Controls.Add(this.grbxPrint);
            this.Controls.Add(this.grbxLocations);
            this.Controls.Add(this.grbxInfo);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.btnPrint);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmMain";
            this.ShowIcon = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Location print";
            this.Load += new System.EventHandler(this.frmDateinamebeispiel_Load);
            this.grbxInfo.ResumeLayout(false);
            this.grbxInfo.PerformLayout();
            this.grbxLocations.ResumeLayout(false);
            this.grbxLocations.PerformLayout();
            this.grbxPrint.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

    }

    private void label15_Click(object sender, EventArgs e)
    {
        throw new NotImplementedException();
    }

    public frmMain()
    {
        InitializeComponent();
    }
    #endregion
    // Details for menu entry and toolbar
    static class ScriptConst
    {
        public const string SCRIPTFAMILIE = "ANTools";
        // Adjust values, depending on the script
        public const string SCRIPTTITEL = "Location Print";
        public const string SCRIPTSTATUSTEXT = "Print after placing";
        public const string SCRIPTACTION = "LocationPrint"; // enter the action manuel in Declare Action!
    }
    
    [DeclareAction("LocationPrint")]
    public void NachPlacentopress()
    {
        frmMain frm = new frmMain();
        frm.ShowDialog();
    }

    [DeclareAction("Info")]
    public void Infofenster()
    {
        MessageBox.Show("ANTools created by Artur Netz");
    }
    // Create menu and toolbar
        [DeclareMenu()]
    public void MenuFunction()
    {
        // Create menu item
        Eplan.EplApi.Gui.Menu oMenu = new Eplan.EplApi.Gui.Menu();
        uint MenueID = oMenu.GetCustomMenuId(ScriptConst.SCRIPTFAMILIE, null);
        if (MenueID == 0) // Recreate menu item
        {
            MenueID = oMenu.AddMainMenu(
            ScriptConst.SCRIPTFAMILIE, // Name: Menu
            "Help", // next...
            ScriptConst.SCRIPTFAMILIE, // Name: Item
            "Info", // Name: Action
            " ", // Statustext
            1 // 1 = Hinter Item, 0 = Vor Item
            );
            oMenu.AddMenuItem(
                ScriptConst.SCRIPTTITEL, // Name: Item
                ScriptConst.SCRIPTACTION, // Name: Action
                ScriptConst.SCRIPTSTATUSTEXT, // Statustext
                MenueID, // Menu-ID: Insert / Window macro... (CTRL + ^ to find Menu - ID)
                0, // 1 = Behind Item, 0 = In Front of Item
                false, // Seperator show it before
                false // Seperator show behind it
                );
        }
        else
        {
            oMenu.AddMenuItem(
                ScriptConst.SCRIPTTITEL, // Name: Item
                ScriptConst.SCRIPTACTION, // Name: Action
                ScriptConst.SCRIPTSTATUSTEXT, // Statustext
                MenueID,
                0, // 1 = Behind Item, 0 = In Front of Item
                false,
                false);
        }
        // Create toolbar
        string symbolBarName = ScriptConst.SCRIPTFAMILIE;
        Eplan.EplApi.Gui.Toolbar symbolBar = new Eplan.EplApi.Gui.Toolbar();
        bool userBar = true;
        // SymbolBar available?
        if (symbolBar.ExistsToolbar(symbolBarName, ref userBar) == false)
        {
            symbolBar.CreateCustomToolbar(symbolBarName, Eplan.EplApi.Gui.Toolbar.ToolBarDockPos.eToolbarFloat, 0, 0, true);
        }
        // Button available?
        bool buttonavailable = false;
        for (int i = 0; i < symbolBar.GetCountOfButtons(symbolBarName); i++)
        {
            string buttonAction = symbolBar.GetButtonAction(symbolBarName, i);
            if (buttonAction == ScriptConst.SCRIPTACTION)
            {
                buttonavailable = true;
            }
        }
        if (buttonavailable == false)
        {
            symbolBar.AddButton(symbolBarName, 0, ScriptConst.SCRIPTACTION, @"$(MD_SCRIPTS)\" + ScriptConst.SCRIPTACTION + @"\Icon\" + ScriptConst.SCRIPTACTION+ @".BMP", ScriptConst.SCRIPTTITEL);
        }
    }

    public class PlaceProjekt
    {
        public static string allePlace;
        public static string[] Place;

        public static string[] getPlace()
        {
            allePlace = auxiliaryfunction.GetAllLocations();
            allePlace.Replace("+", "");
            Char delimiter = '\n';
            Place = allePlace.Split(delimiter);
            return Place;
        }
    }

    private void frmDateinamebeispiel_Load(object sender, EventArgs e)
    {
        string[] Place = PlaceProjekt.getPlace();

        for (int i = 0; i < Place.Length; i++)
        {
            cobxPlace1.Items.Add(Place[i]);
            cobxPlace2.Items.Add(Place[i]);
            cobxPlace3.Items.Add(Place[i]);
            cobxPlace4.Items.Add(Place[i]);
            cobxPlace5.Items.Add(Place[i]);
            cobxPlace6.Items.Add(Place[i]);
            cobxPlace7.Items.Add(Place[i]);
            cobxPlace8.Items.Add(Place[i]);
            cobxPlace9.Items.Add(Place[i]);
            cobxPlace10.Items.Add(Place[i]);
            cobxPlace11.Items.Add(Place[i]);
            cobxPlace12.Items.Add(Place[i]);
        }
        // Determine standard printer
                PrintDocument pd = new PrintDocument();
        string Standarddrucker = pd.PrinterSettings.PrinterName;
        // Discover all printers
        int j = 0;
        int indexstdprinter = 0;
        foreach (string Name in PrinterSettings.InstalledPrinters)
        {
            cobxSelectPrinter.Items.Add(Name);
            if (Name == Standarddrucker)
            {
                indexstdprinter = j;
            }
            j = j + 1;
        }
        // Select standard printer
        cobxSelectPrinter.SelectedIndex = indexstdprinter;
    }

    private static String WildCardToRegular(String value)
    {
        return "^" + Regex.Escape(value).Replace("\\?", ".").Replace("\\*", ".*") + "$";
    }


    private string PlaceSeperate(string input)
    {
        string Placetopress = "";
        string allePlace = "";
        allePlace = PlaceProjekt.allePlace;
        string[] Placeimprojekt;
        string[] inputSplit;
        // String in Array String Aufteilen
        Placeimprojekt = allePlace.Split(default(string[]), StringSplitOptions.RemoveEmptyEntries);
        //Placeimprojekt = allePlace.Split((string[])null, StringSplitOptions.RemoveEmptyEntries);
        //Placeimprojekt = allePlace.Split(null as string[], StringSplitOptions.RemoveEmptyEntries);
        inputSplit = input.Split(';');
        inputSplit = input.Split(default(string[]), StringSplitOptions.RemoveEmptyEntries);
        //inputSplit = input.Split((string[])null, StringSplitOptions.RemoveEmptyEntries);
        //inputSplit = input.Split(null as string[], StringSplitOptions.RemoveEmptyEntries);

        for (int j = 0; j < inputSplit.Length; j++)
        {
            for (int i = 0; i < Placeimprojekt.Length; i++)
            {
                // Comparison with wildcards
                                Boolean endsWithEx = Regex.IsMatch(Placeimprojekt[i], WildCardToRegular(inputSplit[j]));
                if (endsWithEx)
                    {
                    //MessageBox.Show(Placeimprojekt[i]);
                    auxiliaryfunction.GetAllLocationSites(Placeimprojekt[i]);
                    Placetopress = Placetopress + auxiliaryfunction.Placestopress();
                }
            }
        }
        if (Placetopress =="")
        {
            MessageBox.Show("When expression \"" + input + "\" no place was found!", "", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        return Placetopress;
    }
    private void btnPrint_Click(object sender, EventArgs e)
    {
        string Placetopress = "";
        // Generate file with all project pages
        auxiliaryfunction.GetAllSites();

        if (cobxPlace1.Text != "")
        {
            if (chbxPlace1.Checked == true)
            {
                Placetopress = Placetopress + PlaceSeperate(cobxPlace1.Text);
            }
            else
            {
                auxiliaryfunction.GetAllLocationSites(cobxPlace1.Text);
                Placetopress = Placetopress + auxiliaryfunction.Placestopress();
            }
        }
        if (cobxPlace2.Text != "")
        {
            if (chbxPlace2.Checked == true)
            {
                Placetopress = Placetopress + PlaceSeperate(cobxPlace2.Text);
            }
            else
            {
                auxiliaryfunction.GetAllLocationSites(cobxPlace2.Text);
                Placetopress = Placetopress + auxiliaryfunction.Placestopress();
            }
        }
        if (cobxPlace3.Text != "")
        {
            if (chbxPlace3.Checked == true)
            {
                Placetopress = Placetopress + PlaceSeperate(cobxPlace3.Text);
            }
            else
            {
                auxiliaryfunction.GetAllLocationSites(cobxPlace3.Text);
                Placetopress = Placetopress + auxiliaryfunction.Placestopress();
            }
        }
        if (cobxPlace4.Text != "")
        {
            if (chbxPlace4.Checked == true)
            {
                Placetopress = Placetopress + PlaceSeperate(cobxPlace4.Text);
            }
            else
            {
                auxiliaryfunction.GetAllLocationSites(cobxPlace4.Text);
                Placetopress = Placetopress + auxiliaryfunction.Placestopress();
            }
        }
        if (cobxPlace5.Text != "")
        {
            if (chbxPlace5.Checked == true)
            {
                Placetopress = Placetopress + PlaceSeperate(cobxPlace5.Text);
            }
            else
            {
                auxiliaryfunction.GetAllLocationSites(cobxPlace5.Text);
                Placetopress = Placetopress + auxiliaryfunction.Placestopress();
            }
        }
        if (cobxPlace6.Text != "")
        {
            if (chbxPlace6.Checked == true)
            {
                Placetopress = Placetopress + PlaceSeperate(cobxPlace6.Text);
            }
            else
            {
                auxiliaryfunction.GetAllLocationSites(cobxPlace6.Text);
                Placetopress = Placetopress + auxiliaryfunction.Placestopress();
            }
        }
        if (cobxPlace7.Text != "")
        {
            if (chbxPlace7.Checked == true)
            {
                Placetopress = Placetopress + PlaceSeperate(cobxPlace7.Text);
            }
            else
            {
                auxiliaryfunction.GetAllLocationSites(cobxPlace7.Text);
                Placetopress = Placetopress + auxiliaryfunction.Placestopress();
            }
        }
        if (cobxPlace8.Text != "")
        {
            if (chbxPlace8.Checked == true)
            {
                Placetopress = Placetopress + PlaceSeperate(cobxPlace8.Text);
            }
            else
            {
                auxiliaryfunction.GetAllLocationSites(cobxPlace8.Text);
                Placetopress = Placetopress + auxiliaryfunction.Placestopress();
            }
        }
        if (cobxPlace9.Text != "")
        {
            if (chbxPlace9.Checked == true)
            {
                Placetopress = Placetopress + PlaceSeperate(cobxPlace9.Text);
            }
            else
            {
                auxiliaryfunction.GetAllLocationSites(cobxPlace9.Text);
                Placetopress = Placetopress + auxiliaryfunction.Placestopress();
            }
        }
        if (cobxPlace10.Text != "")
        {
            if (chbxPlace10.Checked == true)
            {
                Placetopress = Placetopress + PlaceSeperate(cobxPlace10.Text);
            }
            else
            {
                auxiliaryfunction.GetAllLocationSites(cobxPlace10.Text);
                Placetopress = Placetopress + auxiliaryfunction.Placestopress();
            }
        }
        if (cobxPlace11.Text != "")
        {
            if (chbxPlace11.Checked == true)
            {
                Placetopress = Placetopress + PlaceSeperate(cobxPlace11.Text);
            }
            else
            {
                auxiliaryfunction.GetAllLocationSites(cobxPlace11.Text);
                Placetopress = Placetopress + auxiliaryfunction.Placestopress();
            }
        }
        if (cobxPlace12.Text != "")
        {
            if (chbxPlace12.Checked == true)
            {
                Placetopress = Placetopress + PlaceSeperate(cobxPlace12.Text);
            }
            else
            {
                auxiliaryfunction.GetAllLocationSites(cobxPlace12.Text);
                Placetopress = Placetopress + auxiliaryfunction.Placestopress();
            }
        }

        // topress
        ActionCallingContext actionCallingContext = new ActionCallingContext();
        actionCallingContext.AddParameter("type", "pages");
        actionCallingContext.AddParameter("printername", cobxSelectPrinter.Text);
        // Mehrere pages Parameter erzeugen
        Char delimiter = ' ';
        string[] Place = Placetopress.Split(delimiter);
        for (int i = 0; i < Place.Length; i++)
        {
            actionCallingContext.AddParameter("pagename" + (i - 1), Place[i]);
        }
        // Letzte Abfrage ob wirklich gedruckt werden soll
        if (Placetopress.Length >= 1)
        {
            DialogResult result = MessageBox.Show(Placetopress.Substring(1) + "\nTotal of: " + (Place.Length - 1) + " Pages", "topress?", MessageBoxButtons.YesNo, MessageBoxIcon.Information);
            if (result == DialogResult.Yes)
            {
                new CommandLineInterpreter().Execute("print", actionCallingContext);
            }
            else if (result == DialogResult.No)
            {
                return;
            }
        }
        else
        {
            MessageBox.Show("No pages found to to press!","Info" ,MessageBoxButtons.OK ,MessageBoxIcon.Information);
        }

    }
    private void btnReset_Click(object sender, EventArgs e)
    {
        cobxPlace1.Text = "";
        cobxPlace2.Text = "";
        cobxPlace3.Text = "";
        cobxPlace4.Text = "";
        cobxPlace5.Text = "";
        cobxPlace6.Text = "";
        cobxPlace7.Text = "";
        cobxPlace8.Text = "";
        cobxPlace9.Text = "";
        cobxPlace10.Text = "";
        cobxPlace11.Text = "";
        cobxPlace12.Text = "";

        chbxPlace1.Checked = false;
        chbxPlace2.Checked = false;
        chbxPlace3.Checked = false;
        chbxPlace4.Checked = false;
        chbxPlace5.Checked = false;
        chbxPlace6.Checked = false;
        chbxPlace7.Checked = false;
        chbxPlace8.Checked = false;
        chbxPlace9.Checked = false;
        chbxPlace10.Checked = false;
        chbxPlace11.Checked = false;
        chbxPlace12.Checked = false;
    }
    public class auxiliaryfunction
    {
        public static string GetAllLocations()
        {
            string path = Path.Combine(PathMap.SubstitutePath("$(MD_SCRIPTS)"),
                        "LocationPrint", "Schemes", "[LocationPrint]GetAllLocations.xml");
            string value = "";
            try
            {
                new Settings().ReadSettings(path);
                string pathOutput = Path.Combine(PathMap.SubstitutePath("$(MD_SCRIPTS)"),
                           "LocationPrint", "Schemes", "GetAllLocations_Output.txt");
                File.Delete(pathOutput);

                // ExpPlace
                ActionCallingContext actionCallingContext = new ActionCallingContext();
                actionCallingContext.AddParameter("configscheme", "[LocationPrint]GetAllLocations");
               // actionCallingContext.AddParameter("filterscheme", "[LocationPrint]EinbauPlace");
                actionCallingContext.AddParameter("destinationfile", pathOutput);
                actionCallingContext.AddParameter("language", "en_US");
                new CommandLineInterpreter().Execute("label", actionCallingContext);

                // Read
                value = File.ReadAllText(pathOutput);
            }
            catch (Exception exception)
            {
                MessageBox.Show(exception.Message, "[LocationPrint]GetAllLocations", MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
                value = "[Error]";
            }
            return value;
        }
        // Funktion um alle pages aus EplanProjekt auszulesen
        public static string GetAllSites()
        {
            string path = Path.Combine(PathMap.SubstitutePath("$(MD_SCRIPTS)"),
                        "LocationPrint", "Schemes", "[LocationPrint]GetAllSites.xml");
            string value = "";
            try
            {
                new Settings().ReadSettings(path);
                string pathOutput = Path.Combine(PathMap.SubstitutePath("$(MD_SCRIPTS)"),
                           "LocationPrint", "Schemes", "GetAllSites_Output.txt");
                File.Delete(pathOutput);    // Datei aus letztem Lauf löschen
                // ExpPlace
                ActionCallingContext actionCallingContext = new ActionCallingContext();
                actionCallingContext.AddParameter("configscheme", "[LocationPrint]GetAllSites");
                //actionCallingContext.AddParameter("filterscheme", "[LocationPrint]GetAllSitesFilter");
                actionCallingContext.AddParameter("destinationfile", pathOutput);
                actionCallingContext.AddParameter("language", "en_US");
                new CommandLineInterpreter().Execute("label", actionCallingContext);

                // Read
                value = File.ReadAllText(pathOutput);
            }
            catch (Exception exception)
            {
                MessageBox.Show(exception.Message, "[LocationPrint]GetAllSites", MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
                value = "[Error]";
            }
            return value;
        }
        // Funktion um alle pages aus EplanProjekt auszulesen
        public static string GetAllLocationSites(string Place)
        {
            string path = Path.Combine(PathMap.SubstitutePath("$(MD_SCRIPTS)"),
                        "LocationPrint", "Schemes", "[LocationPrint]GetAllLocationSites.xml");
            string pathtemp = Path.Combine(PathMap.SubstitutePath("$(MD_SCRIPTS)"),
                "LocationPrint", "Schemes", "[LocationPrint]GetAllLocationSitesTemp.xml");
            string value = "";
            string content = string.Empty;
            string filterstring = string.Empty;
            string cleanupstring;
            // Set scheme
            content = File.ReadAllText(pathtemp);
            // cut out the "+" if accidentally typed
                        cleanupstring = Place.Replace("+", "");
            cleanupstring = cleanupstring.Replace("\r", "");
            filterstring = "0|1|0|1220;0|0|" + cleanupstring + "|0|1|1|0|0|0;0|";
            content = content.Replace("FilterLocation", filterstring);
            File.WriteAllText(path, content);

            try
            {
                new Settings().ReadSettings(path);
                string pathOutput = Path.Combine(PathMap.SubstitutePath("$(MD_SCRIPTS)"),
                           "LocationPrint", "Schemes", "GetAllLocationSites_Output.txt");
                File.Delete(pathOutput);    // Datei aus letztem Lauf löschen
                // ExpPlace
                ActionCallingContext actionCallingContext = new ActionCallingContext();
                actionCallingContext.AddParameter("configscheme", "[LocationPrint]GetAllLocationSites");
                //actionCallingContext.AddParameter("filterscheme", "[LocationPrint]GetAllLocationSitesFilter");
                actionCallingContext.AddParameter("destinationfile", pathOutput);
                actionCallingContext.AddParameter("language", "en_US");
                new CommandLineInterpreter().Execute("label", actionCallingContext);
                // Read
                value = File.ReadAllText(pathOutput);
            }
            catch
            {
                MessageBox.Show("Place \"" + Place + "\" was not found!","",MessageBoxButtons.OK, MessageBoxIcon.Information);
                value = "";
            }
            return value;
        }
        // Function to create the printed pages
        public static string Placestopress()
        {
            string tempstring = string.Empty;
            int pagenumber = 0;
            string[] stringarray = new string[1000];
            string pagestopress = string.Empty;
            string path1 = Path.Combine(PathMap.SubstitutePath("$(MD_SCRIPTS)"),
                           "LocationPrint", "Schemes", "GetAllSites_Output.txt");
            string path2 = Path.Combine(PathMap.SubstitutePath("$(MD_SCRIPTS)"),
                           "LocationPrint", "Schemes", "GetAllLocationSites_Output.txt");
            try
            {
                // Read page numbers of the project
                using (StreamReader sr = new StreamReader(path1))
                    tempstring = sr.ReadToEnd();
                string[] separators = { " ", "\n", "\r" };
                string[] readpagenumber = tempstring.Split(separators, StringSplitOptions.RemoveEmptyEntries);
                // Place to be printed read page numbers
                using (StreamReader sr2 = new StreamReader(path2))
                    tempstring = sr2.ReadToEnd();
                string[] printedpages = tempstring.Split(separators, StringSplitOptions.RemoveEmptyEntries);

                // output
                for (int i1 = 0; i1 < readpagenumber.Length; i1++)
                {
                    for (int i2 = 0; i2 < printedpages.Length; i2++)
                    {
                        if (readpagenumber[i1] == printedpages[i2])
                        {
                            //Page found, will be printed
                            pagestopress = pagestopress + " " + readpagenumber[i1];
                            pagenumber = pagenumber + 1;
                            break; // For loop leave
                        }
                    }
                }
            }
            catch
            {
                //   MessageBox.Show("Error during evaluation, printing could not be created");
            }
            return pagestopress;
        }
    }

}
